version: '3'
# Список сервисов (контейнеров)
services:

    rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      healthcheck:
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 1s
        timeout: 3s
        retries: 30
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"
        - "15672:15672"

    app:
      build:
        context: ./
        dockerfile: ./docker/Dockerfile
      depends_on:
        rabbitmq:
          condition: service_healthy
      command: composer install && php console/run worker
      volumes:
        - ./:/var/www/html
      links:
        - rabbitmq